### ISSUE TITLE
Uploader barfs on symlinks

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/atlas-go#23]
When trying to upload and archive a directory that contains symlinks, the archiver gets confused and errors:

```text
$ packer push -create packer.json
Error archiving: failed copying file to archive: /Users/sethvargo/Desktop/test/discourse/adminjs

$ ls -al adminjs
lrwxr-xr-x  1 sethvargo  staff  28 Jan 21 12:31 adminjs -> app/assets/javascripts/admin
```

**Comment by mitchellh** [comment]
I've been trying to fix this for a few hours now. Still working on it, but the bug difficulty level of this is _extreme_. Hah. :)
