### ISSUE TITLE
Symlink issues in packer push

### ISSUE THREAD

**Issue by cbednarski** [hashicorp/atlas-go#39]
Related: https://github.com/mitchellh/packer/issues/2433

**Comment by cbednarski** [comment]
There is a WIP branch for this issue here: [atlas-go/b-symlinks](https://github.com/hashicorp/atlas-go/compare/b-symlinks?expand=1). It includes:

- A new failing test with sample data
- New implementation of symlink unravelling based on go std lib

It still needs some work to track down the problem.

**Comment by RyanBowlby-Reflektion** [comment]
Any further progress on this? Just getting started with packer in Atlas and can't perform a packer push. Here's one obvious and reasonable use case that is going to arise for many, a lib dir in the repository with the normal lib symlinking like so:

```
tree -L 1 lib/
lib/
├── libjson
├── libmaxminddb -> ./libmaxminddb-0.5.5/
├── libmaxminddb-0.5.5
├── libs3 -> ./libs3-2.0/
└── libs3-2.0

5 directories, 0 files
```

**Comment by cbednarski** [comment]
@RyanBowlby-Reflektion As a work-around, can you create the symlinks after the folders are uploaded?

**Comment by RyanBowlby-Reflektion** [comment]
Any update on this? I'm still doing packer builds locally and need to put this in jenkins if it's going to be months not days before I can use packer in Atlas. Thanks!!

**Comment by cbednarski** [comment]
@RyanBowlby-Reflektion Sorry, I don't have an update on this right now. The earliest this might make it into packer is in the next release a few weeks away. Does the workaround I suggested work for you?

**Comment by mak18ah** [comment]
encountered the same issue with symlinks using atlas-upload cli. as a workaround using this [script](http://superuser.com/a/303593) to convert symlinks to file prior to `atlas-upload`

**Comment by RyanBowlby-Reflektion** [comment]
@cbednarski Can you confirm that this bug also impacts use of automatic packer builds from github (github integration)?

I am attempting to setup automatic packer builds from github. I do not plan on "fronting" my atlas packer builds with jenkins or a similar system that would allow swapping of symlinks for duplicate files.

I think this workaround more or less assumes someone is using Atlas with another CI system being the caller. I would like github -> atlas (packer build). Not: github -> jenkins (symlink workaround, packer push) -> atlas (packer build). Am I missing something?

**Comment by cbednarski** [comment]
> I think this workaround more or less assumes someone is using Atlas with another CI system being the caller. I would like github -> atlas (packer build). Not: github -> jenkins (symlink workaround, packer push) -> atlas (packer build). Am I missing something?

@RyanBowlby-Reflektion I was suggesting that this could be accomplished using a [remote shell provisioner](https://www.packer.io/docs/provisioners/shell.html) during the build. This works in any environment (e.g. Atlas, Jenkins, your laptop) since this would be run inside the machine being built.

In your example you indicate that you are using a symlink to alias several folders so (I presume) your application does not need to know which version is installed and can reference the symlink instead:

```
tree -L 1 lib/
lib/
├── libjson
├── libmaxminddb -> ./libmaxminddb-0.5.5/
├── libmaxminddb-0.5.5
├── libs3 -> ./libs3-2.0/
└── libs3-2.0

5 directories, 0 files
```

Since it appears that that libraries `./libmaxminddb-0.5.5/` and `./libs3-2.0/` will still be uploaded (but only the symlink will be missing) you can simply recreate the symlink using a provisioner like this:

```
"provisioners": [
  { "type": "shell",
    "inline": [
      "ln -s /path/lib/libmaxminddb-0.5.5/ /path/lib/libmaxminddb",
      "ln -s /path/lib/libs3-2.0/ /path/lib/libs3"
    ]
  }
]
```

I apologize if I misunderstood your scenario. I understand this workaround is not ideal in any case but hopefully this will unblock you until a proper fix is in place.

**Comment by RyanBowlby-Reflektion** [comment]
@cbednarski Thanks, but the error I receive happens before the directory ever makes it into Atlas. The `packer push` fails when attempting the upload, due to the existence of symlinks. So I don't think a remote shell provisioner is of any use.

Here's the packer push debug excerpt:
``` 
2016/03/14 13:49:10 ui error: Error archiving: lstat /Users/rbowlby/src/github.com/RyanBowlby-Reflektion/Webology/libmaxminddb-0.5.5: no such file or directory
2016/03/14 13:49:10 waiting for all plugin processes to complete...
Error archiving: lstat /Users/rbowlby/src/github.com/company/webapp/libmaxminddb-0.5.5: no such file or directory
```

**Comment by malaikah** [comment]
+1

**Comment by malaikah** [comment]
I think I'm seeing the same issue as is described here. My issue is that symlinks are not being dereferenced correctly. I'm seeing the issue in packer 0.10.1 and 0.12.0. The file structure is the result of composer-installed dependencies. I can't run the composer install as part of the packer build, as it needs to be able to access an internal scm system.

The structure of the files I am trying to push looks like:

build_root/
|-build_dir/
   |-bin/
   |  |- lib1 -> ../vendor/author/lib1/bin/lib
   |
   |- vendor/
      |- author/
         |- lib1/
            |- bin/
               |- lib
When I packer push, I see:

2016/11/23 12:33:00 [INFO] creating archive from /build_root/build_dir
2016/11/23 12:33:01 ui error: Error archiving: lstat /build_root/build_dir/vendor/author/lib1/bin/lib: no such file or directory
2016/11/23 12:33:01 waiting for all plugin processes to complete...
Error archiving: lstat /build_root/build_dir/vendor/author/lib1/bin/lib

I should be able to work around this with some extra scripting to write out the symlinks to a file, remove them, push the file up and recreate them as a packer step, but that's quite involved and gives me another reason to move functionality back out of Atlas and onto Jenkins.

**Comment by mwhooker** [comment]
Here's a PR from @cbednarski's branch: https://github.com/hashicorp/atlas-go/pull/62

There's also a PR here that I understand not as well. https://github.com/hashicorp/atlas-go/pull/59

In order to move this along, it would be helpful if someone who's experienced this issue could test with both PRs and post the results. If we can confirm that one of them works, we can move ahead with closing one out

**Comment by SwampDragons** [comment]
Just merged the PR that @cbednarski referenced.  This is targeted for the next packer release, which is Friday.
