### ISSUE TITLE
Online Logs?

### ISSUE THREAD

**Issue by jakirkham** [hashicorp/atlas-go#43]
It seems that I never get a log for any build. They always just say "Waiting for logs...". This is even true of builds that have finished, successfully or otherwise. It would be really nice if they were live updating. However, it would be nice to see them at all.

**Comment by pearkes** [comment]
Hey @jakirkham! That's very strange – can you email support@hashicorp.com with details about your account? We can take a look from there.

**Comment by jakirkham** [comment]
Ah, sorry. Thanks. Done.
