### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by aviau** [hashicorp/atlas-go#47]
Hello,

It looks like the tests have been failing for six months.

I am packaging atlas-go for Debian and I am wondering what I should do. Were the tests abandoned? Should I disable them?

**Comment by ryanuber** [comment]
Hey @aviau, sorry about that, this should be fixed in f62b42c. It was a simple git file permissions issue, so the tests should pass now. Thanks for reporting this!

**Comment by ryanuber** [comment]
Huh - spoke too soon. Looks like different OS'es are handling this differently, so we'll need to tweak the test helper a little more to make this more generic.

**Comment by ryanuber** [comment]
This is fixed now in b66e377.
